XpenseTracker/Controllers/ExpensesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XpenseTracker.Models;

namespace XpenseTracker.Controllers
{
    public class ExpensesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Expenses
        [Authorize]
        public ActionResult Index()
        {
            var id = User.Identity.GetUserId();
            var Bills = db.Expenses.Where(x => x.User.Id == id).ToList();
            List<ExpenseViewModels> l1 = new List<ExpenseViewModels>();
            foreach (var item in Bills)
            {
                l1.Add(new ExpenseViewModels { Description = item.Description, ExpenseAmount = item.Amount, ExpenseDate = item.ExpenseDate, ExpenseId = item.ExpenseID });
            }
            return View(l1);
        }

        // GET: Expenses/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            ExpenseViewModels v1 = new ExpenseViewModels { Description = expense.Description, ExpenseAmount = expense.Amount, ExpenseDate = expense.ExpenseDate, ExpenseId = expense.ExpenseID };
            return View(v1);
        }

        // GET: Expenses/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

            //Create an expense
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Description,ExpenseAmount,ExpenseDate")] ExpenseViewModels model)
        {
            Expense expense = new Expense();
            if (ModelState.IsValid)
            {
                // Gets the Calendar instance associated with a CultureInfo.
                CultureInfo myCI = new CultureInfo("en-US");
                Calendar myCal = myCI.Calendar;

                // Gets the DTFI properties required by GetWeekOfYear.
                CalendarWeekRule myCWR = myCI.DateTimeFormat.CalendarWeekRule;
                DayOfWeek myFirstDOW = myCI.DateTimeFormat.FirstDayOfWeek;
                var WeekNo = myCal.GetWeekOfYear(model.ExpenseDate, myCWR, myFirstDOW);
                expense = new Expense { Amount = model.ExpenseAmount, Description = model.Description, ExpenseDate = model.ExpenseDate, WeekNo = WeekNo };
                expense.User = db.Users.Find(User.Identity.GetUserId());
                db.Expenses.Add(expense);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        [Authorize]
        // GET: Expenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }

            ExpenseViewModels v1 = new ExpenseViewModels { Description = expense.Description, ExpenseAmount = expense.Amount, ExpenseDate = expense.ExpenseDate, ExpenseId = expense.ExpenseID };
            return View(v1);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpenseId,Description,ExpenseAmount,ExpenseDate")] ExpenseViewModels model)
        {
            Expense expense = new Expense();
            if (ModelState.IsValid)
            {
                // Gets the Calendar instance associated with a CultureInfo.
                CultureInfo myCI = new CultureInfo("en-US");
                Calendar myCal = myCI.Calendar;

                // Gets the DTFI properties required by GetWeekOfYear.
                CalendarWeekRule myCWR = myCI.DateTimeFormat.CalendarWeekRule;
                DayOfWeek myFirstDOW = myCI.DateTimeFormat.FirstDayOfWeek;
                var WeekNo = myCal.GetWeekOfYear(model.ExpenseDate, myCWR, myFirstDOW);
                expense = new Expense { ExpenseID = model.ExpenseId, Amount = model.ExpenseAmount, Description = model.Description, ExpenseDate = model.ExpenseDate, WeekNo = WeekNo };
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expense);
        }

        // GET: Expenses/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expense expense = db.Expenses.Find(id);
            db.Expenses.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET : Get Weekly Report
        [Authorize]
        public ActionResult GetWeeklyReport([Bind(Include = "Start,End")] ExpenseWeeklyViewModel model)
        {
            // Gets the Calendar instance associated with a CultureInfo.
            CultureInfo myCI = new CultureInfo("en-US");
            Calendar myCal = myCI.Calendar;

            // Gets the DTFI properties required by GetWeekOfYear.
            CalendarWeekRule myCWR = myCI.DateTimeFormat.CalendarWeekRule;
            DayOfWeek myFirstDOW = myCI.DateTimeFormat.FirstDayOfWeek;
            var id = User.Identity.GetUserId();
            var Bills = db.Expenses.Where(x => x.User.Id == id).ToList();
            if (model.Start != null && model.End != null)
            {
                Bills = Bills.Where(x => x.ExpenseDate >= model.Start && x.ExpenseDate <= model.End).ToList();
            }

            //var groupedByWeek = Bills.GroupBy(i => SqlFunctions.DatePart("week", i.ExpenseDate));
            ExpenseWeeklyViewModel expenseWeeklyViewModel = new ExpenseWeeklyViewModel();
            List<ExpenseWeeklyViewRecord> WeeklyReport = Bills.GroupBy(l => l.WeekNo).Select(cl => new ExpenseWeeklyViewRecord
            {
                //Start = FirstDateOfWeekISO8601(cl.First().ExpenseDate.Year, cl.First().WeekNo),
                //End = FirstDateOfWeekISO8601(cl.First().ExpenseDate.Year, cl.First().WeekNo).AddDays(6),
                Start = GetFirstDayOfWeek(cl.First().ExpenseDate.Year, cl.First().WeekNo, myCI).AddDays(-7),
                End = GetFirstDayOfWeek(cl.First().ExpenseDate.Year, cl.First().WeekNo, myCI).AddDays(-1),
                Sum = cl.Sum(c => c.Amount),
            }).OrderBy(x=>x.Start).ToList();
            expenseWeeklyViewModel.ExpenseRecords = WeeklyReport;
            return View(expenseWeeklyViewModel);
        }
        //GET : Get Admin Listing
        [Authorize(Roles ="Admin")]
        public ActionResult GetAdminList()
        {
            var Expenses = db.Expenses.ToList();
            List<ExpenseAdminListingViewModels> List1 = Expenses.Select(cl => new ExpenseAdminListingViewModels { FirstName = cl.User.FirstName, LastName = cl.User.LastName, Description = cl.Description, ExpenseAmount = cl.Amount, ExpenseDate = cl.ExpenseDate }).ToList();
            return View(List1);
        }
        // GET : Get Range
        [Authorize]
        public ActionResult GetRange()
        {
            return View();
        }

        // PUT: Get Range
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRange([Bind(Include = "Start,End")] ExpenseViewRangeModels model)
        {
            var id = User.Identity.GetUserId();
            var Bills = db.Expenses.Where(x => x.User.Id == id).ToList();
            Bills = Bills.Where(x => x.ExpenseDate >= model.Start && x.ExpenseDate <= model.End).ToList();
            List<ExpenseWeeklyViewRecord> WeeklyReport = Bills.GroupBy(l => l.WeekNo).Select(cl => new ExpenseWeeklyViewRecord
            {
                Start = FirstDateOfWeekISO8601(cl.First().ExpenseDate.Year, cl.First().WeekNo),
                End = FirstDateOfWeekISO8601(cl.First().ExpenseDate.Year, cl.First().WeekNo).AddDays(6),
                Sum = cl.Sum(c => c.Amount),
            }).ToList();
            ExpenseWeeklyViewModel expenseWeeklyViewModel = new ExpenseWeeklyViewModel();
            expenseWeeklyViewModel.ExpenseRecords = WeeklyReport;
            return View("GetWeeklyReport", expenseWeeklyViewModel);

        }

        //Day from weekNo

        public static DateTime FirstDateOfWeekISO8601(int year, int weekOfYear)
        {
            DateTime jan1 = new DateTime(year, 1, 1);
            int daysOffset = DayOfWeek.Thursday - jan1.DayOfWeek;

            DateTime firstThursday = jan1.AddDays(daysOffset);

XpenseTracker/Views/Expenses/Create.cshtml
@model XpenseTracker.Models.ExpenseViewModels

@{
    ViewBag.Title = "Create";
}

<h2>Add a bill.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.ExpenseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

XpenseTracker/Views/Expenses/Delete.cshtml
@model XpenseTracker.Models.Expense

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpenseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpenseDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

XpenseTracker/Views/Expenses/Details.cshtml
@model XpenseTracker.Models.ExpenseViewModels

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpenseAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpenseAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpenseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpenseDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ExpenseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

XpenseTracker/Views/Expenses/Edit.cshtml
@model XpenseTracker.Models.ExpenseViewModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ExpenseId)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.ExpenseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

XpenseTracker/Views/Expenses/GetAdminList.cshtml
@model IEnumerable<XpenseTracker.Models.ExpenseAdminListingViewModels>

@{
    ViewBag.Title = "Get Admin List";
}

<h2>Expenses</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("First Name")
        </th>
        <th>
            @Html.DisplayName("Last Name")
        </th>
        <th>
            @Html.DisplayName("Description")
        </th>
        <th>
            @Html.DisplayName("Date and time")
        </th>
        <th>
            @Html.DisplayName("Amount")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.ExpenseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseAmount)
            </td>
        </tr>
    }

</table>

XpenseTracker/Views/Expenses/GetRange.cshtml
@model XpenseTracker.Models.ExpenseViewRangeModels
@{
    ViewBag.Title = "GetRange";
}

<h2>Enter the range</h2>

@using (@Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-inline">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 pull-right">
                        @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control col-md-2 datepicker" } })
                        @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 pull-right">
                        @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control col-md-2 datepicker" } })
                        @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="form-group ">
            <div class="col-md-offset-0 col-md-10">
                <input type="submit" value="Find" class="btn btn-default" />
            </div>
        </div>
    </div>
}

XpenseTracker/Views/Expenses/GetWeeklyReport.cshtml
@model XpenseTracker.Models.ExpenseWeeklyViewModel
@{
    ViewBag.Title = "GetWeeklyReport";
}

<h2>Weekly Report</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Start date")
        </th>
        <th>
            @Html.DisplayName("End Date")
        </th>
        <th>
            @Html.DisplayName("Total")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.ExpenseRecords)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sum)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ExpenseID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ExpenseID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ExpenseID })
                </td>*@
        </tr>
    }
</table>
@*@Html.ActionLink("Filter Expense", "GetRange", "Expenses")*@

<h4>Enter the range</h4>

@using (@Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-inline">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => Model.Start, htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 pull-right">
                        @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control col-md-5 datepicker" } })
                        @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7 pull-right">
                        @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control col-md-5 datepicker start"} })
                        @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="form-group ">
            <div class="col-md-offset-0 col-md-10">
                <input type="submit" value="Find" class="btn btn-default" />
            </div>
        </div>
    </div>
}

XpenseTracker/Views/Expenses/Index.cshtml
@model IEnumerable<XpenseTracker.Models.ExpenseViewModels>

@{
    ViewBag.Title = "Expenses";
}

<h2>Expenses</h2>

<p>
    @Html.ActionLink("Add Expense", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Description")
        </th>
        <th>
            @Html.DisplayName("Amount")
        </th>
        <th>
            @Html.DisplayName("Date and time")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpenseAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpenseDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ExpenseId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ExpenseId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ExpenseId })
        </td>
    </tr>
}

</table>

XpenseTracker/Views/Expenses/_GetRangeList.cshtml
@model IEnumerable<XpenseTracker.Models.Expense>

@{
    ViewBag.Title = "GetRangeList";
    double sum = 0;
}

<h2>My bills</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpenseDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        sum += item.Amount;
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ExpenseID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ExpenseID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ExpenseID })
            </td>
        </tr>
    }

</table>
<div class="form-inline">
    <h3>Total: @sum</h3>
</div>